const make = (level, rows) => rows.map(([id,group,name,hint,description,examples]) => ({id,level,group,name,hint,description,examples}));
const grammar = [
...make('middle',[
['be','基本の文','be動詞','am / are / is','「〜です」「〜にいます」を表し、主語に合わせて形を変えます。疑問文では主語の前に置きます。',[['I am a student.','私は学生です。'],['They are in the library.','彼らは図書館にいます。'],['Is she your sister?','彼女はあなたのお姉さんですか？']]],
['present','基本の文','一般動詞・現在形','Present simple','習慣や事実を表します。he / she / it が主語のときは動詞に s または es をつけます。',[['I usually walk to school.','私はたいてい歩いて学校へ行きます。'],['Ken plays the guitar after dinner.','ケンは夕食後にギターを弾きます。'],['Does your brother like soccer?','あなたのお兄さんはサッカーが好きですか？']]],
['past','基本の文','過去形','Past simple','過去に起きたことを表します。規則動詞には ed をつけ、不規則動詞は形が変わります。',[['I visited Kyoto last spring.','私は去年の春、京都を訪れました。'],['She made dinner for her family.','彼女は家族のために夕食を作りました。'],['Did you see the game yesterday?','昨日その試合を見ましたか？']]],
['future','基本の文','未来表現','will / be going to','will は予測やその場での決定、be going to は予定や根拠のある予測によく使います。',[['I will call you tomorrow.','明日あなたに電話します。'],['We are going to visit Nara this weekend.','私たちは今週末、奈良を訪れる予定です。'],['It is going to rain. Look at those clouds.','雨が降りそうです。あの雲を見て。']]],
['questions','基本の文','疑問文・否定文','Questions & negatives','be動詞・助動詞は前に出し、一般動詞は do / does / did を使います。',[['Do you speak English?','英語を話しますか？'],['He does not eat meat.','彼は肉を食べません。'],['Where did they go?','彼らはどこへ行きましたか？']]],
['continuous','時制','現在進行形','Present continuous','今していることを表します。be動詞 + 動詞の ing 形が基本です。',[['I’m learning something new.','私は新しいことを学んでいます。'],['He is making coffee right now.','彼は今、コーヒーを淹れています。'],['What are you reading?','何を読んでいるの？']]],
['past-cont','時制','過去進行形','Past continuous','過去のある時点で進行中だった動作を表します。was / were + 動詞の ing 形です。',[['I was studying at nine last night.','昨夜9時、私は勉強していました。'],['They were playing tennis when it started to rain.','雨が降り始めたとき、彼らはテニスをしていました。']]],
['perfect','時制','現在完了形','Present perfect','過去と現在とのつながりを表します。経験・継続・完了の用法があり、have / has + 過去分詞で作ります。',[['I have been to London twice.','ロンドンに2回行ったことがあります。'],['She has lived here for five years.','彼女はここに5年間住んでいます。'],['We have just finished lunch.','私たちはちょうど昼食を終えたところです。']]],
['modal','表現を広げる','助動詞','can / must / should','可能・義務・助言などの意味を加えます。助動詞の後ろは動詞の原形です。',[['You can use my computer.','私のパソコンを使ってもいいですよ。'],['We must leave before six.','私たちは6時前に出発しなければなりません。'],['You should get some rest.','少し休んだほうがいいですよ。']]],
['infinitive','表現を広げる','不定詞','to + 動詞の原形','「〜すること」「〜するために」「〜するための」のように、名詞・副詞・形容詞の働きをします。',[['I want to learn French.','私はフランス語を学びたいです。'],['She went to the store to buy milk.','彼女は牛乳を買うために店へ行きました。'],['I have a lot of homework to do.','私にはやるべき宿題がたくさんあります。']]],
['gerund','表現を広げる','動名詞','動詞 + ing','動詞の ing 形が「〜すること」という名詞の働きをします。',[['I enjoy cooking for my friends.','友達のために料理をするのが好きです。'],['He finished reading the book.','彼はその本を読み終えました。'],['Walking every day is good for you.','毎日歩くことは健康によいです。']]],
['comparison','表現を広げる','比較・最上級','Comparatives','2つを比べる比較級、3つ以上の中の最上級、同じくらいを表す表現を学びます。',[['This bag is lighter than that one.','このかばんはあのかばんより軽いです。'],['She is the tallest student in her class.','彼女はクラスでいちばん背が高い生徒です。'],['My room is as big as yours.','私の部屋はあなたの部屋と同じくらい大きいです。']]],
['passive','表現を広げる','受け身','Passive voice','「〜される」と、動作を受ける側を主語にします。be動詞 + 過去分詞で作ります。',[['This picture was painted by my aunt.','この絵は私のおばによって描かれました。'],['English is spoken in many countries.','英語は多くの国で話されています。']]],
['there','表現を広げる','There is / are','存在を表す文','人や物が「〜にいる・ある」と伝える表現です。be動詞は後ろの名詞に合わせます。',[['There is a small park near my house.','私の家の近くに小さな公園があります。'],['There are three apples on the table.','テーブルの上にりんごが3つあります。']]],
['relative-middle','文をつなぐ','関係代名詞（基礎）','who / which / that','人や物の説明を後ろから加えて、2つの文をつなぎます。',[['I have a friend who lives in Canada.','私にはカナダに住んでいる友達がいます。'],['This is the book that I bought yesterday.','これは私が昨日買った本です。']]],
['conjunction','文をつなぐ','接続詞','and / but / because','語や文をつなぎ、理由・時・逆接などの関係を表します。',[['I stayed home because I was tired.','疲れていたので家にいました。'],['Call me when you get home.','家に着いたら電話してください。']]]
]),
...make('high',[
['patterns','文のしくみ','5文型','Sentence patterns','文の骨格を S・V・O・C で捉えます。動詞によって後ろに続く形が変わります。',[['Birds fly. (SV)','鳥は飛びます。'],['She gave me a present. (SVOO)','彼女は私にプレゼントをくれました。'],['The news made him happy. (SVOC)','その知らせは彼を幸せにしました。']]],
['tense','時制・助動詞','時制と完了形','Tense & aspect','現在・過去・未来と進行・完了を組み合わせ、いつのどんな状態かを表します。',[['I have been waiting for an hour.','私は1時間ずっと待っています。'],['She had left before I arrived.','私が着く前に彼女は出発していました。'],['By next June, he will have graduated.','来年の6月までには、彼は卒業しているでしょう。']]],
['future-forms','時制・助動詞','未来進行形・未来完了形','Future forms','未来のある時点で進行中の動作や、その時点までに完了している動作を表します。',[['This time tomorrow, I will be flying to Osaka.','明日の今ごろ、私は大阪へ飛行中でしょう。'],['She will have finished the report by noon.','正午までには彼女はレポートを仕上げているでしょう。']]],
['modals','時制・助動詞','助動詞の使い分け','Modals & nuance','推量・義務・後悔など、助動詞と完了形の組み合わせで細かな意味を表します。',[['You must be tired after the trip.','旅行のあとで疲れているに違いありません。'],['You should have told me earlier.','もっと早く私に言ってくれればよかったのに。'],['He may have missed the last train.','彼は終電に乗り遅れたのかもしれません。']]],
['infinitive','準動詞','不定詞の応用','Infinitives','意味上の主語・完了形・受け身などを使い、不定詞の時や動作主も表します。',[['It is important for us to listen carefully.','私たちが注意深く聞くことが大切です。'],['She seems to have forgotten the appointment.','彼女は約束を忘れてしまったようです。']]],
['gerund','準動詞','動名詞の応用','Gerunds','意味上の主語や受け身形を使います。動詞によって後ろが動名詞か不定詞か変わる点にも注意。',[['I remember meeting her at the conference.','会議で彼女に会ったことを覚えています。'],['He insisted on paying for dinner.','彼は夕食代を払うと言って譲りませんでした。']]],
['participles','準動詞','分詞','Participles','現在分詞・過去分詞で名詞を修飾したり、補語として状態や感情を表したりします。',[['The girl standing by the window is my cousin.','窓のそばに立っている女の子は私のいとこです。'],['I found the door locked.','私はドアに鍵がかかっているのに気づきました。']]],
['participle-clause','準動詞','分詞構文','Participial constructions','分詞を使って理由・時・条件などを簡潔に表します。意味上の主語や完了形にも注目します。',[['Walking along the river, I found a quiet café.','川沿いを歩いていて、静かなカフェを見つけました。'],['Having finished her work, she went home.','仕事を終えてから、彼女は帰宅しました。']]],
['relative','文をつなぐ','関係詞の応用','Relative clauses','関係代名詞・関係副詞・what 節で名詞を詳しく説明したり、文の要素をまとめたりします。',[['This is the house where I grew up.','ここは私が育った家です。'],['What she said surprised everyone.','彼女が言ったことは皆を驚かせました。'],['My uncle, who lives in Kyoto, is a chef.','京都に住んでいる私のおじは料理人です。']]],
['noun-clause','文をつなぐ','名詞節','That / whether / if','that・whether・疑問詞などで始まる節が、文の中で主語・目的語・補語になります。',[['I believe that she will succeed.','彼女は成功すると信じています。'],['Whether we go depends on the weather.','行くかどうかは天気次第です。'],['Do you know where he put the keys?','彼が鍵をどこに置いたか知っていますか？']]],
['adverb-clause','文をつなぐ','副詞節・接続表現','Adverb clauses','時・理由・条件・譲歩などの関係を表す節を作り、文と文の論理関係を明確にします。',[['I will wait here until you come back.','あなたが戻るまでここで待ちます。'],['Although it was cold, we went for a walk.','寒かったけれど、私たちは散歩に出かけました。']]],
['conditionals','仮定・比較','仮定法','Conditionals','現実とは異なる仮定や願望を表します。現在・過去の事実と時制のずれに注目します。',[['If I had more time, I would learn Italian.','もっと時間があれば、イタリア語を学ぶのに。'],['If she had left earlier, she could have caught the train.','もっと早く出ていれば、彼女は電車に間に合ったのに。'],['I wish I were on vacation now.','今休暇中だったらいいのに。']]],
['subjunctive','仮定・比較','要求・提案の that 節','Mandative subjunctive','提案・要求・必要性を表す語に続く that 節では、動詞の原形を使う形があります。',[['The doctor suggested that he rest for a few days.','医師は彼に数日休むよう勧めました。'],['It is essential that everyone be on time.','全員が時間どおりであることが不可欠です。']]],
['comparison','仮定・比較','比較表現の応用','Advanced comparison','the 比較級、倍数表現などで、複雑な比較を作ります。',[['The more you practice, the more confident you become.','練習すればするほど、自信がつきます。'],['This box is three times as heavy as that one.','この箱はあの箱の3倍の重さです。']]],
['passive','文のしくみ','受け身の応用','Advanced passive','助動詞・進行形・完了形を含む受け身や、目的語を主語にする形を学びます。',[['The road is being repaired now.','その道路は今、修理されています。'],['The package should have been delivered yesterday.','その荷物は昨日配達されているはずでした。'],['She was given a chance to explain.','彼女は説明する機会を与えられました。']]],
['reported-speech','文のしくみ','話法','Reported speech','発言や質問を間接的に伝えます。時制・代名詞・時を表す語の変化に注意します。',[['He said that he was busy.','彼は忙しいと言いました。'],['She asked me where I had bought the bag.','彼女は私に、そのかばんをどこで買ったのか尋ねました。']]],
['inversion','文のしくみ','倒置・強調・省略','Inversion & emphasis','語順を変えたり語句を強調したりして、意味に焦点を当てます。',[['Never have I seen such a beautiful view.','こんなに美しい景色を見たことがありません。'],['It was Tom who found the missing key.','なくした鍵を見つけたのはトムでした。'],['I can play the piano, and my sister can, too.','私はピアノが弾けますし、姉も弾けます。']]]
])
];
grammar.push(
...make('middle',[
['nouns','基本の文','名詞・冠詞・複数形','Nouns & articles','名詞の数え方に合わせて a / an・the・複数形を使います。',[['I bought an umbrella.','私は傘を1本買いました。'],['The books on the desk are mine.','机の上の本は私のものです。']]],
['pronouns','基本の文','代名詞・所有格','Pronouns','主語・目的語・所有など、文中の役割に合わせて代名詞の形を変えます。',[['This is my pen. Is that yours?','これは私のペンです。あれはあなたのものですか？'],['I gave her a small gift.','私は彼女に小さな贈り物をあげました。']]],
['prepositions','基本の文','前置詞','Prepositions','場所・時・方向など、名詞とほかの語の関係を表します。',[['The keys are on the table.','鍵はテーブルの上にあります。'],['We have lunch at noon.','私たちは正午に昼食をとります。']]],
['imperative','基本の文','命令文・感嘆文','Imperatives','命令・依頼・誘いかけや、強い感情を表します。',[['Please open the window.','窓を開けてください。'],['What a beautiful day!','なんてすばらしい日でしょう！']]],
['indirect-question','文をつなぐ','疑問詞・間接疑問文','Wh- & indirect questions','疑問詞で始まる疑問文と、文の中に疑問を含める間接疑問文を学びます。',[['What time does the store open?','その店は何時に開きますか？'],['Do you know where she lives?','彼女がどこに住んでいるか知っていますか？']]]
]),
...make('high',[
['causative-perception','文のしくみ','使役・知覚動詞','Causative & perception','make・let・have や see・hear の後ろに続く目的語と補語の形を学びます。',[['The coach made us run five laps.','コーチは私たちに5周走らせました。'],['I heard someone call my name.','誰かが私の名前を呼ぶのが聞こえました。']]],
['negation','文のしくみ','否定・部分否定','Negation','not only・not always など、否定の範囲によって意味が変わる表現を学びます。',[['Not all birds can fly.','すべての鳥が飛べるわけではありません。'],['I have never seen such a thing.','そんなものを見たことが一度もありません。']]],
['agreement','文のしくみ','主語と動詞の一致','Subject-verb agreement','主語の数や人称に動詞を一致させます。長い主語や不定代名詞にも注意します。',[['Each of the students has a locker.','生徒はそれぞれロッカーを持っています。'],['The number of visitors is increasing.','訪問者数は増えています。']]],
['omission','文のしくみ','省略・代用','Ellipsis & substitution','同じ語句の繰り返しを避けるため、助動詞や代名詞で置き換える表現を学びます。',[['I enjoyed the concert, and so did my sister.','私はコンサートを楽しみましたし、姉もそうでした。'],['You may borrow my bike if you want to.','よければ私の自転車を借りてもいいですよ。']]]
])
);
const options=document.querySelector('#grammar-options'),list=document.querySelector('#example-list'),search=document.querySelector('#search-input'),tabs=document.querySelectorAll('.level-button');
let activeLevel='middle',activeId='be',query='',utterance=null;
const visibleGrammar=()=>grammar.filter(item=>item.level===activeLevel);
function renderOptions(){const items=visibleGrammar();document.querySelector('#grammar-count').textContent=`${items.length}項目`;const groups=[...new Set(items.map(item=>item.group))];options.innerHTML=groups.map(group=>`<div class="grammar-group-label">${group}</div>`+items.filter(item=>item.group===group).map(item=>`<button class="grammar-option ${item.id===activeId?'selected':''}" type="button" data-id="${item.id}" aria-pressed="${item.id===activeId}"><span class="grammar-name">${item.name}</span></button>`).join('')).join('')}
function renderExamples(){const selected=grammar.find(item=>item.id===activeId);if(!selected)return;document.querySelector('#selected-title').textContent=selected.name;document.querySelector('#grammar-description').textContent=selected.description;const filtered=selected.examples.filter(([en,ja])=>`${en} ${ja}`.toLowerCase().includes(query.toLowerCase()));document.querySelector('#result-count').textContent=`例文 ${filtered.length}件`;list.innerHTML=filtered.length?filtered.map(([en,ja])=>`<article class="example-card"><div><div class="example-english" lang="en">${en}</div><p class="example-japanese">${ja}</p></div><button class="audio-button" type="button" aria-label="${en} を再生" title="英文を読み上げる" data-speak="${en.replaceAll('&','&amp;').replaceAll('"','&quot;')}">▶</button></article>`).join(''):'<div class="empty-state">見つかりませんでした。</div>'}
function revealExamples(){document.querySelector('.examples-panel').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
options.addEventListener('click',event=>{const button=event.target.closest('[data-id]');if(!button)return;activeId=button.dataset.id;query='';search.value='';renderOptions();renderExamples();revealExamples()});
tabs.forEach(tab=>tab.addEventListener('click',()=>{activeLevel=tab.dataset.level;activeId=visibleGrammar()[0].id;query='';search.value='';tabs.forEach(item=>{const on=item===tab;item.classList.toggle('active',on);item.setAttribute('aria-pressed',String(on))});renderOptions();renderExamples()}));
search.addEventListener('input',()=>{query=search.value.trim();renderExamples()});
document.addEventListener('click',event=>{const button=event.target.closest('[data-speak]');if(!button)return;if(!('speechSynthesis'in window)){button.title='このブラウザは音声読み上げに対応していません';return}window.speechSynthesis.cancel();document.querySelectorAll('.audio-button.playing').forEach(el=>{el.classList.remove('playing');el.textContent='▶'});utterance=new SpeechSynthesisUtterance(button.dataset.speak);utterance.lang='en-US';utterance.rate=.88;utterance.onstart=()=>{button.classList.add('playing');button.textContent='Ⅱ'};utterance.onend=utterance.onerror=()=>{button.classList.remove('playing');button.textContent='▶'};window.speechSynthesis.speak(utterance)});
renderOptions();renderExamples();
